/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechnicalRouteImport } from './routes/technical'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TechnicalSlugRouteImport } from './routes/technical.$slug'
import { Route as NotesSlugRouteImport } from './routes/notes.$slug'

const TechnicalRoute = TechnicalRouteImport.update({
  id: '/technical',
  path: '/technical',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalSlugRoute = TechnicalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TechnicalRoute,
} as any)
const NotesSlugRoute = NotesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NotesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notes': typeof NotesRouteWithChildren
  '/technical': typeof TechnicalRouteWithChildren
  '/notes/$slug': typeof NotesSlugRoute
  '/technical/$slug': typeof TechnicalSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notes': typeof NotesRouteWithChildren
  '/technical': typeof TechnicalRouteWithChildren
  '/notes/$slug': typeof NotesSlugRoute
  '/technical/$slug': typeof TechnicalSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notes': typeof NotesRouteWithChildren
  '/technical': typeof TechnicalRouteWithChildren
  '/notes/$slug': typeof NotesSlugRoute
  '/technical/$slug': typeof TechnicalSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/notes' | '/technical' | '/notes/$slug' | '/technical/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/notes' | '/technical' | '/notes/$slug' | '/technical/$slug'
  id:
    | '__root__'
    | '/'
    | '/notes'
    | '/technical'
    | '/notes/$slug'
    | '/technical/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotesRoute: typeof NotesRouteWithChildren
  TechnicalRoute: typeof TechnicalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/technical': {
      id: '/technical'
      path: '/technical'
      fullPath: '/technical'
      preLoaderRoute: typeof TechnicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical/$slug': {
      id: '/technical/$slug'
      path: '/$slug'
      fullPath: '/technical/$slug'
      preLoaderRoute: typeof TechnicalSlugRouteImport
      parentRoute: typeof TechnicalRoute
    }
    '/notes/$slug': {
      id: '/notes/$slug'
      path: '/$slug'
      fullPath: '/notes/$slug'
      preLoaderRoute: typeof NotesSlugRouteImport
      parentRoute: typeof NotesRoute
    }
  }
}

interface NotesRouteChildren {
  NotesSlugRoute: typeof NotesSlugRoute
}

const NotesRouteChildren: NotesRouteChildren = {
  NotesSlugRoute: NotesSlugRoute,
}

const NotesRouteWithChildren = NotesRoute._addFileChildren(NotesRouteChildren)

interface TechnicalRouteChildren {
  TechnicalSlugRoute: typeof TechnicalSlugRoute
}

const TechnicalRouteChildren: TechnicalRouteChildren = {
  TechnicalSlugRoute: TechnicalSlugRoute,
}

const TechnicalRouteWithChildren = TechnicalRoute._addFileChildren(
  TechnicalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotesRoute: NotesRouteWithChildren,
  TechnicalRoute: TechnicalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
